[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
version = "0.5.0"
license = "MIT OR Apache-2.0 OR CC0-1.0"
exclude = ["assets/"]
description = "The all-in-one Bevy 3D game template for desktop."
repository = "https://github.com/janhohenheim/foxtrot"
keywords = ["gamedev", "bevy", "template", "game"]
categories = ["game-development"]
homepage = "https://janhohenheim.github.io/foxtrot/"

[features]
default = ["dev"]
dev = [
    "dep:bevy-inspector-egui",
    "bevy/file_watcher",
    "bevy/dynamic_linking",
    "oxidized_navigation/debug_draw",
]
tracing = ["bevy/trace_chrome"]

[dependencies.bevy]
version = "0.14.1"
features = [
    "jpeg",
]

[dependencies]
# keep the following in sync with Bevy's dependencies
## https://github.com/bevyengine/bevy/blob/v0.14.1/crates/bevy_winit/Cargo.toml#L35
winit = { version = "0.30", default-features = false }
## https://github.com/bevyengine/bevy/blob/v0.14.1/crates/bevy_render/Cargo.toml#L65
image = { version = "0.25.2", default-features = false }
## This greatly improves WGPU's performance due to its heavy use of trace! calls
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

# generic dependencies
serde = { version = "1", features = ["derive"] }
anyhow = "1"

# Bevy plugins
bevy_kira_audio = "0.20"
bevy_asset_loader = { version = "0.21", features = ["progress_tracking", "standard_dynamic_assets"] }
bevy_common_assets = { version = "0.11", features = ["ron", "toml"] }
#bevy_egui = "0.25" # version governed by bevy_editor_pls and leafwing-input-manager
oxidized_navigation = { version = "0.11", features = ["xpbd"] }
iyes_progress = "0.12"
leafwing-input-manager = "0.14"
bevy_dolly = "0.0.4"
bevy-inspector-egui = { version = "0.25.0", optional = true }
bevy_hanabi = { version = "0.12", default-features = false, features = ["3d"] }
bevy_yarnspinner = "0.3"
bevy_yarnspinner_example_dialogue_view = "0.3"
bevy-tnua-avian3d = "0.1"
avian3d = { version = "0.1", features = ["simd"] }
bevy-tnua = "0.19"
bevy_atmosphere = "0.10"
#warbler_grass = "0.6"
blenvy = { git = "https://github.com/kaosat-dev/blenvy", branch = "blenvy" }

[build-dependencies]
embed-resource = "2"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# High optimizations for distributing the game
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
