[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
version = "0.1.10"
license = "MIT OR  Apache-2.0"
exclude = ["dist", "build", "assets", "credits", "saves", "resources", "build.rs"]
description = "The all-in-one Bevy 3D game template."
repository = "https://github.com/janhohenheim/foxtrot"
keywords = ["gamedev", "bevy", "template", "game"]
categories = ["game-development"]
homepage = "https://janhohenheim.github.io/foxtrot/"

[features]
default = [
    "native-dev",
]

core = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/hdr",
    "bevy/png",
    "bevy/jpeg",
    "bevy/bevy_asset",
    "bevy/x11",
    "bevy/animation",
    "bevy/serialize",
]

dev = [
    "dep:bevy_editor_pls",
    "dep:bevy_prototype_debug_lines",
    "core"
]

native-dev = [
    "bevy/dynamic",
    "bevy/filesystem_watcher",
    "dev",
    "native"
]

native = [
    "bevy_rapier3d/parallel",
    "dep:bevy_hanabi",
    "core"
]

wasm = [
    "bevy_rapier3d/wasm-bindgen",
    "core",
    "dep:wasm-bindgen",
]

wasm_dev = [
    "wasm",
    "dev"
]

tracing = [
    "bevy/trace_chrome"
]

[dependencies]
bevy = { version = "^0.9.1", default-features = false }
bevy_kira_audio = "0.13"
bevy_asset_loader = { version = "0.14.1", features = ["progress_tracking"] }
bevy_common_assets = { version = "0.4.0", features = ["ron", "toml"] }
bevy_egui = "0.19"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "1", features = ["serde-1"] }
strum = "0.24.1"
strum_macros = "0.24.3"
ron = "0.8.0"
regex = "1"
chrono = "0.4.23"
glob = "0.3.1"
oxidized_navigation = "0.2.0"
bitflags = "1.3.2"
iyes_progress = "0.7.1"
unicode-segmentation = "1.10.1"
bevy_hanabi = { version = "0.5", optional = true }
anyhow = "1.0.69"
bevy_rapier3d = { version = "0.20", features = ["serde-serialize", "simd-nightly"] }
leafwing-input-manager = { version = "0.8.0", features = [ "egui" ] }
bevy_editor_pls = { version = "0.2", optional = true}
bevy_prototype_debug_lines = { version = "0.9.0", optional = true, features = ["3d"] }
wasm-bindgen = { version = "0.2.84", optional = true }
warblersneeds = { git = "https://github.com/EmiOnGit/warblersneeds.git", rev = "331fc84ac7178d10a55a70aacf6008d1e71a8f97" } # Not on crates.io yet
rand = { version = "0.8.5", features = ["small_rng", "nightly"] }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.27", default-features = false }
image = { version = "0.24", default-features = false }

[build-dependencies]
embed-resource = "1.4"

[patch.crates-io]
leafwing-input-manager = { git = "https://github.com/TimJentzsch/leafwing-input-manager.git", branch = "307-scancode-support" } # https://github.com/Leafwing-Studios/leafwing-input-manager/pull/312
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader.git", rev = "be7f9005db76224912a06742ed521557262b50fe" } # Collections as maps feature
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls", rev = "6062b860aea87034081399369fd7ef5715f13256" } # Smaller bug fixes
bevy_hanabi = { git = "https://github.com/janhohenheim/bevy_hanabi" } # https://github.com/djeedai/bevy_hanabi/issues/144
