[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
publish = false
version = "0.1.4"
license = "MIT or Apache-2.0"
exclude = ["dist", "build", "assets", "credits", "saves", "resources"]

[features]
default = [
    "core",
    "dynamic",
]

core = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/hdr",
    "bevy/png",
    "bevy/jpeg",
    "bevy/x11",
    "bevy/animation",
    "bevy/serialize",
    "bevy_kira_audio/ogg",
]

dev = [
    "dep:bevy_editor_pls",
    "dep:bevy_prototype_debug_lines",
    "bevy/filesystem_watcher",
]

dynamic = [
    "bevy/dynamic",
]

[dependencies]
bevy = { version = "^0.9.1", default-features = false }
bevy_kira_audio = "0.13"
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader.git", rev = "9a7966c9e7a44026a2192292390b315d28c88ca7", features = ["3d", "standard_dynamic_assets"] }
bevy_common_assets = { version = "0.4.0", features = ["ron"] }
bevy_egui = "0.19"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "1", features = ["serde-1"] }
strum = "0.24.1"
strum_macros = "0.24.3"
ron = "0.8.0"
regex = "1"
chrono = "0.4.23"
glob = "0.3.1"
polyanya = "0.2.0"
bevy_pathmesh = "0.3.0"

# keep the following in sync with Bevy's dependencies
winit = { version = "0.27", default-features = false }
image = { version = "0.24", default-features = false }

[dependencies.bevy_prototype_debug_lines]
version = "0.9.0"
optional = true
features = ["3d"]

[dependencies.bevy_editor_pls]
git = "https://github.com/jakobhellermann/bevy_editor_pls"
rev = "6062b860aea87034081399369fd7ef5715f13256"
optional = true

[dependencies.bevy_rapier3d]
git = "https://github.com/janhohenheim/bevy_rapier"
branch = "own-fork"
features = [
    "debug-render-3d",
    "simd-nightly",
    "parallel",
    "serde-serialize",
]

[build-dependencies]
embed-resource = "1.4"

