[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
version = "0.3.0"
license = "MIT OR Apache-2.0"
exclude = [
    "dist/",
    "saves/",
    "assets/",
    "resources/",
]
description = "The all-in-one Bevy 3D game template for desktop."
repository = "https://github.com/janhohenheim/foxtrot"
keywords = ["gamedev", "bevy", "template", "game"]
categories = ["game-development"]
homepage = "https://janhohenheim.github.io/foxtrot/"

[features]
default = ["dev"]
dev = ["dep:bevy_editor_pls"]
tracing = ["bevy/trace_chrome"]

[dependencies]
bevy_kira_audio = "0.18"
bevy_asset_loader = { version = "0.19", features = ["progress_tracking"] }
bevy_common_assets = { version = "0.9", features = ["ron", "toml"] }
bevy_egui = "0.24"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
strum = "0.26"
strum_macros = "0.26"
ron = "0.8"
regex = "1"
chrono = "0.4"
glob = "0.3"
oxidized_navigation = { version = "0.8", features = ["rapier", "debug_draw"] }
bitflags = "2"
iyes_progress = "0.10"
unicode-segmentation = "1"
anyhow = "1"
# Activate the egui feature when https://github.com/Leafwing-Studios/leafwing-input-manager/pull/442 lands
leafwing-input-manager = { version = "0.11", features = [] }
rand = { version = "0.8", features = ["small_rng"] }
bevy_dolly = "0.0.2"
spew = "0.4"
bevy_mod_sysfail = "5"
seldom_fn_plugin = "0.5"
# https://github.com/TheGrimsey/oxidized_navigation/pull/21
bevy_rapier3d = { version = "0.23", features = [ "serde-serialize", "simd-stable", "parallel" ] }
bevy_editor_pls = { version = "0.7", optional = true }
bevy_hanabi = "0.9"

# https://github.com/yarn-slinger/yarn-slinger/issues/172
bevy_yarn_slinger = { git = "https://github.com/yarn-slinger/yarn-slinger", rev = "b6fb6d5f7f5982a165758fa4da61ea6ebf1ef6b1" }
bevy_yarn_slinger_example_dialogue_view = { git = "https://github.com/yarn-slinger/yarn-slinger", rev = "b6fb6d5f7f5982a165758fa4da61ea6ebf1ef6b1" }

# keep the following in sync with Bevy's dependencies
## https://github.com/bevyengine/bevy/blob/v0.12.1/crates/bevy_winit/Cargo.toml#L31
winit = { version = "0.28.7", default-features = false }
## https://github.com/bevyengine/bevy/blob/v0.12.1/crates/bevy_render/Cargo.toml#L57
image = { version = "0.24", default-features = false }

[dependencies.bevy]
version = "0.12"
features = [
    "jpeg",
    "serialize",
    #"dynamic_linking", causes issues on Windows
    "file_watcher",
]

[build-dependencies]
embed-resource = "2"
