inherits = "/textures/base.toml"

[material]
base_color = { Srgba = { red = 0.6, green = 0.6, blue = 0.6, alpha = 1.0 } }
metallic_roughness_texture = "${name}/${name}_roughness.png"
metallic = 0.0
perceptual_roughness = 1.0
