name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly

jobs:
  test-native:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Install zld
        run: brew install michaeleisel/zld/zld
        if: runner.os == 'macos'
      - name: Install llvm tools
        run: cargo install -f cargo-binutils && rustup component add llvm-tools-preview
        if: runner.os == 'windows'
      - name: Build & run tests for native
        run: cargo test
  test-native-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run doc tests
        run: cargo test --doc
  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "v0.16.0"
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build wasm
        run: trunk build --no-default-features --features wasm_dev
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          components: rustfmt, clippy
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Run clippy with native dev features
        run: cargo clippy --workspace --all-targets -- --deny warnings
      - name: Run clippy with native release features
        run: cargo clippy --workspace --all-targets --no-default-features --features native -- --deny warnings
      - name: Run clippy with wasm dev features
        run: cargo clippy --workspace --all-targets --no-default-features --features wasm_dev -- --deny warnings
      - name: Run clippy with wasm release features
        run: cargo clippy --workspace --all-targets --no-default-features --features wasm -- --deny warnings
